# Generated by Django 5.1.2 on 2024-10-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_menu', '0002_authormodel_remove_productmodel_category_bookmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='image',
        ),
    ]
